### PR TITLE
fix bug where earcut() faces have backwards winding

### PR DESCRIPTION
**Pull request by robbykraft**

### CODE REVIEW

**Comment by robbykraft** [comment]
an example of a FOLD file i was using for testing http://robbykraft.github.io/Origami/files/fold/crane.fold which of course could have errors on their own but to double check winding i've been using jason's FOLD viewer

**Comment by edemaine** [comment]
I agree that that file is much happier with this patch.  I also found [the earcut bug](https://github.com/mapbox/earcut/issues/44) that is causing this.  But I'm a little unclear whether reversing everything is always the right thing &mdash; should we instead preserve the given orientations, as in the patches mentioned in the earcut issue?  I'm especially concerned about the 3D case...

I'm also confused why `triangulatePolys` always gets called with `is2d` set to `true`.  As a result, earcut gets only the x and y coordinate of each point, with no z coordinate.  Actually, if I'm reading things correctly, it gets the x coordinate and zero, because the y coordinate is put in the 3rd position not the 2nd (yuck).  Should we actually use the 3D mode of earcut?

**Comment by edemaine** [comment]
This PR also seems to break the built-in Maze Foldings / origami simulator example (just selected from the Examples menu): it seems to flip the same faces that are incorrect in #21 (so that bug may be related to this earcut issue too).  Turning off `is2d` didn't seem to help...

image

**Comment by edemaine** [comment]
Replaced by #32.

**Pull request closed without merging**
